[package]
name = "mirrorbone"
version = "0.1.0"
authors = ["a <no@no.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.13"
rand = "0.8.3"
termimage = "1.1.0"
